import type { Niche } from '@/lib/niches'
import type { ResearchRecord } from '@/services/researchV2/types'

/**
 * Sample research dataset for offline tests and demo pipeline runs.
 * Descriptive market observations only — no copyrighted artwork.
 */
export const SAMPLE_RESEARCH_DATASET: Array<{
  topic: string
  niche: Niche
  sources: string[]
  records: Omit<ResearchRecord, 'topic' | 'niche' | 'detectedAt'>[]
}> = [
  {
    topic: 'Chaotic orange cat house takeover',
    niche: 'pets',
    sources: ['serpapi', 'etsy', 'curated', 'google_trends'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 72,
        searchInterest: 78,
        engagementSignals: 70,
        commercialSignals: 82,
        buyerIntent: 80,
        seasonality: 40,
        competition: 68,
        visualPatterns: ['oversized cat character', 'destroyed household props', 'bold outlines'],
        recurringPhrases: ['my cat owns', 'house rules', 'cat dad', 'need this'],
        productTypes: ['tshirt', 'mug', 'sticker'],
        priceRange: { min: 18, max: 35, currency: 'USD' },
        audience: 'cat parents 25-45',
        demographicSignals: ['pet parents', 'gift buyers'],
        designPatterns: ['mascot illustration', 'comic exaggeration', 'banner typography'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'One more game night owl gamer',
    niche: 'gaming',
    sources: ['serpapi', 'curated', 'google_trends'],
    records: [
      {
        source: 'serpapi',
        trendVelocity: 80,
        searchInterest: 74,
        engagementSignals: 76,
        commercialSignals: 71,
        buyerIntent: 68,
        seasonality: 35,
        competition: 72,
        visualPatterns: ['exhausted gamer mascot', 'glowing monitors', 'retro arcade colors'],
        recurringPhrases: ['one more game', 'literally me', 'take my money'],
        productTypes: ['tshirt', 'hoodie', 'mug'],
        audience: 'gamers 18-35',
        demographicSignals: ['gamers', 'streamers'],
        designPatterns: ['retro arcade', 'neon', 'comic'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Beer league baseball dad',
    niche: 'baseball',
    sources: ['etsy', 'serpapi'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 55,
        searchInterest: 66,
        engagementSignals: 52,
        commercialSignals: 77,
        buyerIntent: 74,
        seasonality: 70,
        competition: 60,
        visualPatterns: ['vintage baseball card frame', 'distressed bat', 'arched varsity type'],
        recurringPhrases: ['beer league', 'dad gift', 'perfect gift'],
        productTypes: ['tshirt', 'hoodie', 'hat'],
        audience: 'baseball dads 30-50',
        demographicSignals: ['dads', 'gift'],
        designPatterns: ['vintage americana', 'sports poster', 'distressed screenprint'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Softball tournament snack mom',
    niche: 'softball',
    sources: ['etsy', 'curated'],
    records: [
      {
        source: 'curated',
        trendVelocity: 58,
        searchInterest: 62,
        engagementSignals: 55,
        commercialSignals: 75,
        buyerIntent: 78,
        seasonality: 72,
        competition: 55,
        visualPatterns: ['mitt mascot', 'snack chaos', 'team badge'],
        recurringPhrases: ['tournament mom', 'where can I buy', 'team gift'],
        productTypes: ['tshirt', 'hoodie', 'tote'],
        audience: 'softball parents',
        demographicSignals: ['parents', 'team'],
        designPatterns: ['sports poster', 'mascot', 'college graphic'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Teacher coffee survival mode',
    niche: 'teacher',
    sources: ['serpapi', 'etsy', 'curated'],
    records: [
      {
        source: 'serpapi',
        trendVelocity: 64,
        searchInterest: 80,
        engagementSignals: 68,
        commercialSignals: 84,
        buyerIntent: 82,
        seasonality: 78,
        competition: 78,
        visualPatterns: ['exploding coffee cup rocket', 'sticky notes armor'],
        recurringPhrases: ['teacher life', 'need coffee', 'perfect gift'],
        productTypes: ['tshirt', 'mug', 'tote'],
        audience: 'teachers',
        demographicSignals: ['educators', 'gift'],
        designPatterns: ['mascot illustration', 'bold streetwear'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Night shift nurse caffeine hero',
    niche: 'nurse',
    sources: ['etsy', 'serpapi'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 60,
        searchInterest: 76,
        engagementSignals: 64,
        commercialSignals: 80,
        buyerIntent: 79,
        seasonality: 40,
        competition: 70,
        visualPatterns: ['stethoscope creature', 'coffee IV drip cartoon'],
        recurringPhrases: ['night shift', 'nurse life', 'my girlfriend needs this'],
        productTypes: ['tshirt', 'hoodie', 'mug'],
        audience: 'nurses',
        demographicSignals: ['healthcare', 'gift'],
        designPatterns: ['mascot', 'comic book'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Sarcastic office humor tee',
    niche: 'humor',
    sources: ['serpapi', 'google_trends', 'curated'],
    records: [
      {
        source: 'serpapi',
        trendVelocity: 70,
        searchInterest: 72,
        engagementSignals: 74,
        commercialSignals: 69,
        buyerIntent: 65,
        seasonality: 30,
        competition: 82,
        visualPatterns: ['kinetic type block', 'lightning through letters'],
        recurringPhrases: ['this is literally me', 'need this'],
        productTypes: ['tshirt', 'sticker'],
        audience: 'office humor fans',
        demographicSignals: ['gift', 'young adult'],
        designPatterns: ['bold streetwear', 'y2k'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Y2K neon bubble nostalgia',
    niche: 'retro',
    sources: ['serpapi', 'curated', 'etsy'],
    records: [
      {
        source: 'curated',
        trendVelocity: 68,
        searchInterest: 70,
        engagementSignals: 72,
        commercialSignals: 66,
        buyerIntent: 60,
        seasonality: 35,
        competition: 65,
        visualPatterns: ['bubble multi-color letters', 'daisy letter swap', 'chrome outlines'],
        recurringPhrases: ['Y2K', 'hot and flashy', 'take my money'],
        productTypes: ['tshirt', 'hoodie', 'poster'],
        audience: 'millennials / gen z fashion',
        demographicSignals: ['fashion', 'festival'],
        designPatterns: ['y2k', 'neon 80s', 'vaporwave'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Bookish TBR guilt pile',
    niche: 'bookish',
    sources: ['etsy', 'curated'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 52,
        searchInterest: 68,
        engagementSignals: 58,
        commercialSignals: 73,
        buyerIntent: 70,
        seasonality: 45,
        competition: 58,
        visualPatterns: ['chubby book character', 'page tornado'],
        recurringPhrases: ['TBR', 'book club', 'perfect gift'],
        productTypes: ['tshirt', 'tote', 'mug', 'sticker'],
        audience: 'readers',
        demographicSignals: ['readers', 'gift'],
        designPatterns: ['cute kawaii', 'animal illustration', 'hand-drawn'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Pickle baseball dad humor',
    niche: 'baseball',
    sources: ['serpapi', 'etsy', 'curated'],
    records: [
      {
        source: 'serpapi',
        trendVelocity: 75,
        searchInterest: 61,
        engagementSignals: 80,
        commercialSignals: 58,
        buyerIntent: 55,
        seasonality: 60,
        competition: 45,
        visualPatterns: ['pickle character in batting stance', 'vintage card frame'],
        recurringPhrases: ['pickle', 'dad humor', 'where can I get this'],
        productTypes: ['tshirt', 'sticker'],
        audience: 'quirky sports fans',
        demographicSignals: ['dads', 'viral humor'],
        designPatterns: ['food illustration', 'vintage baseball card', 'comic'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Frog gaming sarcasm',
    niche: 'gaming',
    sources: ['curated', 'google_trends'],
    records: [
      {
        source: 'curated',
        trendVelocity: 77,
        searchInterest: 58,
        engagementSignals: 82,
        commercialSignals: 48,
        buyerIntent: 45,
        seasonality: 25,
        competition: 50,
        visualPatterns: ['original frog mascot with headset', 'retro arcade cabinet'],
        recurringPhrases: ['need this', 'literally me'],
        productTypes: ['tshirt', 'sticker', 'mug'],
        audience: 'meme-adjacent gamers',
        demographicSignals: ['gamers', 'meme'],
        designPatterns: ['retro arcade', 'mascot', 'sticker bomb'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Camping badge coffee outdoor',
    niche: 'humor',
    sources: ['etsy'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 40,
        searchInterest: 55,
        engagementSignals: 42,
        commercialSignals: 70,
        buyerIntent: 68,
        seasonality: 65,
        competition: 50,
        visualPatterns: ['circular patch badge', 'campfire + mug'],
        recurringPhrases: ['camping gift', 'perfect gift'],
        productTypes: ['tshirt', 'hoodie', 'sticker'],
        audience: 'outdoor casual',
        demographicSignals: ['gift', 'outdoors'],
        designPatterns: ['camping badge', 'outdoor adventure'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Halloween teacher spooky classroom',
    niche: 'teacher',
    sources: ['serpapi', 'etsy', 'google_trends', 'curated'],
    records: [
      {
        source: 'serpapi',
        trendVelocity: 85,
        searchInterest: 88,
        engagementSignals: 70,
        commercialSignals: 86,
        buyerIntent: 84,
        seasonality: 95,
        competition: 80,
        visualPatterns: ['cute spooky apple ghost', 'classroom chaos'],
        recurringPhrases: ['halloween teacher', 'perfect gift'],
        productTypes: ['tshirt', 'mug', 'tote'],
        audience: 'teachers seasonal',
        demographicSignals: ['teachers', 'seasonal gift'],
        designPatterns: ['cute kawaii', 'comic', 'mascot'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Christmas gamer ugly sweater energy',
    niche: 'gaming',
    sources: ['serpapi', 'etsy'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 70,
        searchInterest: 75,
        engagementSignals: 60,
        commercialSignals: 78,
        buyerIntent: 80,
        seasonality: 92,
        competition: 75,
        visualPatterns: ['controller with santa hat original', 'snow + neon'],
        recurringPhrases: ['gamer gift', 'christmas', 'secret santa'],
        productTypes: ['hoodie', 'tshirt', 'mug'],
        audience: 'gamer gift buyers',
        demographicSignals: ['gift', 'holiday'],
        designPatterns: ['retro arcade', 'comic', 'bold streetwear'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Official licensed NFL mashup attempt',
    niche: 'baseball',
    sources: ['serpapi'],
    records: [
      {
        source: 'serpapi',
        trendVelocity: 90,
        searchInterest: 95,
        engagementSignals: 88,
        commercialSignals: 90,
        buyerIntent: 85,
        seasonality: 50,
        competition: 95,
        visualPatterns: ['team jersey lookalikes'],
        recurringPhrases: ['official', 'licensed', 'authentic'],
        productTypes: ['tshirt'],
        audience: 'sports fans',
        demographicSignals: ['fans'],
        designPatterns: ['sports poster'],
        riskSignals: ['nfl', 'licensed', 'official'],
      },
    ],
  },
  {
    topic: 'Dog mom zoomies chaos',
    niche: 'pets',
    sources: ['etsy', 'serpapi', 'curated'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 66,
        searchInterest: 79,
        engagementSignals: 71,
        commercialSignals: 83,
        buyerIntent: 81,
        seasonality: 35,
        competition: 74,
        visualPatterns: ['dog tornado leash', 'smug sunglasses pup'],
        recurringPhrases: ['dog mom', 'need this', 'my husband needs this'],
        productTypes: ['tshirt', 'hoodie', 'mug', 'sticker'],
        audience: 'dog parents',
        demographicSignals: ['pet parents', 'gift'],
        designPatterns: ['animal illustration', 'comic', 'sticker bomb'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Retro arcade controller rage',
    niche: 'retro',
    sources: ['curated', 'serpapi'],
    records: [
      {
        source: 'curated',
        trendVelocity: 62,
        searchInterest: 60,
        engagementSignals: 65,
        commercialSignals: 58,
        buyerIntent: 55,
        seasonality: 30,
        competition: 55,
        visualPatterns: ['pixel-adjacent invented shapes', 'joystick mascot'],
        recurringPhrases: ['arcade', 'insert coin'],
        productTypes: ['tshirt', 'poster'],
        audience: 'retro gamers',
        demographicSignals: ['nostalgia'],
        designPatterns: ['retro arcade', 'neon 80s'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Nurse graduation gift set',
    niche: 'nurse',
    sources: ['etsy', 'curated'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 48,
        searchInterest: 70,
        engagementSignals: 50,
        commercialSignals: 85,
        buyerIntent: 88,
        seasonality: 60,
        competition: 62,
        visualPatterns: ['hero cape glove', 'grad cap on stethoscope creature'],
        recurringPhrases: ['graduation', 'nurse gift', 'perfect gift'],
        productTypes: ['tshirt', 'mug', 'tote'],
        audience: 'nursing grads + families',
        demographicSignals: ['graduation', 'gift'],
        designPatterns: ['mascot', 'college graphic'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Book club wine and chapters',
    niche: 'bookish',
    sources: ['etsy'],
    records: [
      {
        source: 'etsy',
        trendVelocity: 44,
        searchInterest: 57,
        engagementSignals: 48,
        commercialSignals: 72,
        buyerIntent: 70,
        seasonality: 40,
        competition: 52,
        visualPatterns: ['book + wine glass original characters'],
        recurringPhrases: ['book club', 'gift for her'],
        productTypes: ['tshirt', 'tote', 'mug'],
        audience: 'book clubs',
        demographicSignals: ['gift', 'women 25-45'],
        designPatterns: ['vintage tattoo', 'cute kawaii'],
        riskSignals: [],
      },
    ],
  },
  {
    topic: 'Softball dirt never bothered me',
    niche: 'softball',
    sources: ['serpapi', 'etsy', 'curated', 'google_trends'],
    records: [
      {
        source: 'serpapi',
        trendVelocity: 63,
        searchInterest: 65,
        engagementSignals: 60,
        commercialSignals: 76,
        buyerIntent: 73,
        seasonality: 75,
        competition: 58,
        visualPatterns: ['dirt explosion mitt', 'arched athletic type'],
        recurringPhrases: ['softball life', 'tournament', 'team gift'],
        productTypes: ['tshirt', 'hoodie', 'hat'],
        audience: 'softball athletes + parents',
        demographicSignals: ['athletes', 'parents'],
        designPatterns: ['sports poster', 'distressed screenprint', 'mascot'],
        riskSignals: [],
      },
    ],
  },
]
